"""
Service runtime.

``ServiceRunner`` is the single entry point a service author uses to:

- Start an async gRPC server
- Bind a configurable list of servicers
- Enable gRPC reflection so clients can discover methods
- Enable the standard gRPC health check protocol
- Register the service with Consul using the (possibly OS-assigned) port
- Deregister + shut down gracefully on SIGINT/SIGTERM/SIGBREAK

Usage (simplified)::

    runner = ServiceRunner(
        service_name="hello",
        servicers=[(hello_pb2_grpc.add_HelloServiceServicer_to_server,
                    hello_pb2.DESCRIPTOR.services_by_name["HelloService"].full_name,
                    HelloGrpcAdapter(domain))],
        settings=settings,
    )
    await runner.serve_forever()

The ``servicers`` argument is a list of tuples:
``(register_fn, full_service_name, servicer_instance)``.
"""

from __future__ import annotations

import asyncio
import logging
import signal
from dataclasses import dataclass
from typing import Awaitable, Callable, List, Optional, Sequence, Tuple

import grpc
from grpc_health.v1 import health, health_pb2, health_pb2_grpc

from .consul import ConsulRegistration
from .reflection import enable_reflection
from .settings import BaseServiceSettings

logger = logging.getLogger(__name__)


# ``register_fn(servicer, server)`` — the function generated by grpcio_tools,
# named like ``add_HelloServiceServicer_to_server``.
RegisterFn = Callable[[object, grpc.aio.Server], None]


@dataclass
class ServicerEntry:
    """
One gRPC servicer to bind to the server.

**Attributes:**

* ``register_fn``

  / *Type*: callable /

  The ``add_<Name>Servicer_to_server`` function generated by
  ``grpcio_tools``.

* ``full_service_name``

  / *Type*: str /

  Fully-qualified proto service name (e.g. ``"hello.v1.HelloService"``).
  Used for reflection + optional Consul metadata.

* ``servicer``

  / *Type*: object /

  The servicer instance implementing the RPCs.
    """

    register_fn: RegisterFn
    full_service_name: str
    servicer: object


class ServiceRunner:
    """
Run an async gRPC service with Consul registration and graceful shutdown.

``settings.service_name`` must be non-empty; it's the logical name other
services and the GUI use to find this one.
    """

    def __init__(
        self,
        servicers: Sequence[ServicerEntry],
        settings: BaseServiceSettings,
        tags: Optional[Sequence[str]] = None,
        shutdown_grace_sec: float = 5.0,
    ) -> None:
        """
Construct a ServiceRunner.

**Arguments:**

* ``servicers``

  / *Condition*: required / *Type*: Sequence[ServicerEntry] /

  List of :class:`ServicerEntry` describing what to expose.

* ``settings``

  / *Condition*: required / *Type*: BaseServiceSettings /

  The service's settings instance (a :class:`BaseServiceSettings`
  subclass).

* ``tags``

  / *Condition*: optional / *Type*: Sequence[str] / *Default*: None /

  Optional Consul tags written to the registration record.

* ``shutdown_grace_sec``

  / *Condition*: optional / *Type*: float / *Default*: 5.0 /

  Grace period (seconds) for in-flight RPCs to drain on shutdown.
        """
        if not settings.service_name:
            raise ValueError("settings.service_name must be set")

        self._servicers = list(servicers)
        self._settings = settings
        self._tags = list(tags or [])
        self._shutdown_grace = shutdown_grace_sec

        self._server: Optional[grpc.aio.Server] = None
        self._health_servicer: Optional[health.HealthServicer] = None
        self._bound_port: int = 0
        self._stop_event = asyncio.Event()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def start(self) -> int:
        """
Start the gRPC server and register with Consul.

**Returns:**

* ``port``

  / *Type*: int /

  The port the server is bound to.  Same as ``settings.grpc_port`` when
  that value is non-zero, or the OS-assigned port when it was ``0``.
        """
        self._server = grpc.aio.server()

        # Bind user servicers.
        for entry in self._servicers:
            entry.register_fn(entry.servicer, self._server)

        # Standard gRPC health check service — Consul uses this to probe us.
        self._health_servicer = health.HealthServicer()
        health_pb2_grpc.add_HealthServicer_to_server(
            self._health_servicer, self._server
        )

        # Reflection so the GUI and grpcurl can enumerate methods.
        reflection_names = [e.full_service_name for e in self._servicers]
        reflection_names.append(health_pb2.DESCRIPTOR.services_by_name["Health"].full_name)
        enable_reflection(self._server, reflection_names)

        # Bind the listen port (possibly dynamic).
        bind_target = f"{self._settings.service_host}:{self._settings.grpc_port}"
        self._bound_port = self._server.add_insecure_port(bind_target)
        if self._bound_port == 0:
            raise RuntimeError(f"Failed to bind gRPC server on {bind_target}")

        await self._server.start()
        logger.info(
            "gRPC server listening on %s:%d",
            self._settings.service_host, self._bound_port,
        )

        # Mark every servicer SERVING so the health check passes.
        for entry in self._servicers:
            self._health_servicer.set(
                entry.full_service_name, health_pb2.HealthCheckResponse.SERVING
            )
        # Overall service health (empty name) also SERVING.
        self._health_servicer.set("", health_pb2.HealthCheckResponse.SERVING)

        return self._bound_port

    async def serve_forever(self) -> None:
        """
Start, register with Consul, and block until a shutdown signal arrives.

**Returns:**

(*no returns*)
        """
        port = await self.start()

        self._install_signal_handlers()

        address = self._settings.advertise_addr or _local_hostname()

        meta = {
            "grpc_services": ",".join(e.full_service_name for e in self._servicers),
        }

        async with ConsulRegistration(
            name=self._settings.service_name,
            address=address,
            port=port,
            consul_addr=self._settings.consul_addr,
            tags=self._tags,
            meta=meta,
            token=self._settings.consul_token,
        ):
            logger.info("Service %s ready.", self._settings.service_name)
            await self._stop_event.wait()
            await self._graceful_shutdown()

    def request_shutdown(self) -> None:
        """
Trigger graceful shutdown.  Safe to call from a signal handler.

**Returns:**

(*no returns*)
        """
        if not self._stop_event.is_set():
            logger.info("Shutdown requested.")
            self._stop_event.set()

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    async def _graceful_shutdown(self) -> None:
        """
Drain in-flight RPCs and stop the server.

**Returns:**

(*no returns*)
        """
        if self._health_servicer is not None:
            self._health_servicer.enter_graceful_shutdown()
        if self._server is not None:
            logger.info("Stopping gRPC server (grace=%.1fs)...", self._shutdown_grace)
            await self._server.stop(self._shutdown_grace)
        logger.info("Service stopped cleanly.")

    def _install_signal_handlers(self) -> None:
        """
Wire SIGINT / SIGTERM / SIGBREAK to ``request_shutdown``.

**Returns:**

(*no returns*)
        """
        loop = asyncio.get_running_loop()

        def _handler(signame: str) -> None:
            logger.info("Received %s.", signame)
            self.request_shutdown()

        # SIGTERM / SIGINT always.  SIGBREAK on Windows (Ctrl+Break).
        for sig_name in ("SIGINT", "SIGTERM", "SIGBREAK"):
            sig = getattr(signal, sig_name, None)
            if sig is None:
                continue
            try:
                loop.add_signal_handler(sig, _handler, sig_name)
            except NotImplementedError:
                # Windows asyncio doesn't support add_signal_handler —
                # fall back to signal.signal which runs on the main thread.
                signal.signal(sig, lambda s, f, n=sig_name: _handler(n))


def _local_hostname() -> str:
    """
Return a usable IPv4 address for Consul advertising.

Uses :func:`socket.getaddrinfo` with ``AF_INET`` to make sure we never
announce an IPv6 address — on Windows + Python 3.13,
``gethostbyname(gethostname())`` can return ``::1`` even though the
function is nominally IPv4-only, and Consul's gRPC health check will
fail to connect to it because our gRPC server binds ``0.0.0.0``
(IPv4 only).  Falls back to ``127.0.0.1`` if resolution fails.

**Returns:**

* ``addr``

  / *Type*: str /

  An IPv4 ``host`` string suitable for Consul advertising.
    """
    import socket
    try:
        infos = socket.getaddrinfo(socket.gethostname(), None,
                                   family=socket.AF_INET,
                                   type=socket.SOCK_STREAM)
        for info in infos:
            addr = info[4][0]
            if addr and ":" not in addr:      # sanity-check IPv4
                return addr
    except Exception:  # noqa: BLE001
        pass
    return "127.0.0.1"
