# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hello_pb2 as hello__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hello_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HelloServiceStub(object):
    """HelloService — minimal demo service for the new MicroserviceBase runtime.

    Every RPC uses typed request/response messages.  The old `svc_api_*` naming
    convention is gone; method discovery is handled via gRPC reflection.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Greet = channel.unary_unary(
                '/hello.v1.HelloService/Greet',
                request_serializer=hello__pb2.GreetRequest.SerializeToString,
                response_deserializer=hello__pb2.GreetResponse.FromString,
                _registered_method=True)
        self.Echo = channel.unary_unary(
                '/hello.v1.HelloService/Echo',
                request_serializer=hello__pb2.EchoRequest.SerializeToString,
                response_deserializer=hello__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.Tick = channel.unary_stream(
                '/hello.v1.HelloService/Tick',
                request_serializer=hello__pb2.TickRequest.SerializeToString,
                response_deserializer=hello__pb2.TickEvent.FromString,
                _registered_method=True)


class HelloServiceServicer(object):
    """HelloService — minimal demo service for the new MicroserviceBase runtime.

    Every RPC uses typed request/response messages.  The old `svc_api_*` naming
    convention is gone; method discovery is handled via gRPC reflection.
    """

    def Greet(self, request, context):
        """Return a friendly greeting.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """Echo the input back unchanged.  Useful for latency measurement.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tick(self, request, context):
        """Stream N ticks, one per second.  Demonstrates server streaming and is how
        real-time updates (e.g. Cleware switch state changes) will be delivered
        now that the RabbitMQ fanout exchange is gone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Greet': grpc.unary_unary_rpc_method_handler(
                    servicer.Greet,
                    request_deserializer=hello__pb2.GreetRequest.FromString,
                    response_serializer=hello__pb2.GreetResponse.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=hello__pb2.EchoRequest.FromString,
                    response_serializer=hello__pb2.EchoResponse.SerializeToString,
            ),
            'Tick': grpc.unary_stream_rpc_method_handler(
                    servicer.Tick,
                    request_deserializer=hello__pb2.TickRequest.FromString,
                    response_serializer=hello__pb2.TickEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.v1.HelloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hello.v1.HelloService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HelloService(object):
    """HelloService — minimal demo service for the new MicroserviceBase runtime.

    Every RPC uses typed request/response messages.  The old `svc_api_*` naming
    convention is gone; method discovery is handled via gRPC reflection.
    """

    @staticmethod
    def Greet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hello.v1.HelloService/Greet',
            hello__pb2.GreetRequest.SerializeToString,
            hello__pb2.GreetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hello.v1.HelloService/Echo',
            hello__pb2.EchoRequest.SerializeToString,
            hello__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hello.v1.HelloService/Tick',
            hello__pb2.TickRequest.SerializeToString,
            hello__pb2.TickEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
