# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x08hello.v1\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rGreetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07payload\x18\x01 \x01(\t\"1\n\x0bTickRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x13\n\x0binterval_ms\x18\x02 \x01(\x05\".\n\tTickEvent\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb5\x01\n\x0cHelloService\x12\x38\n\x05Greet\x12\x16.hello.v1.GreetRequest\x1a\x17.hello.v1.GreetResponse\x12\x35\n\x04\x45\x63ho\x12\x15.hello.v1.EchoRequest\x1a\x16.hello.v1.EchoResponse\x12\x34\n\x04Tick\x12\x15.hello.v1.TickRequest\x1a\x13.hello.v1.TickEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GREETREQUEST']._serialized_start=25
  _globals['_GREETREQUEST']._serialized_end=53
  _globals['_GREETRESPONSE']._serialized_start=55
  _globals['_GREETRESPONSE']._serialized_end=87
  _globals['_ECHOREQUEST']._serialized_start=89
  _globals['_ECHOREQUEST']._serialized_end=119
  _globals['_ECHORESPONSE']._serialized_start=121
  _globals['_ECHORESPONSE']._serialized_end=152
  _globals['_TICKREQUEST']._serialized_start=154
  _globals['_TICKREQUEST']._serialized_end=203
  _globals['_TICKEVENT']._serialized_start=205
  _globals['_TICKEVENT']._serialized_end=251
  _globals['_HELLOSERVICE']._serialized_start=254
  _globals['_HELLOSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
