// HelloGrpcAdapter.h — Inbound adapter: maps gRPC calls to HelloService.
//
// Inherits from the code generated by protoc/grpc_cpp_plugin
// (hello::v1::HelloService::Service).

#pragma once

#include <grpcpp/grpcpp.h>

#include "hello.grpc.pb.h"
#include "domain/HelloService.h"

namespace hello {

class HelloGrpcAdapter final : public hello::v1::HelloService::Service {
public:
    explicit HelloGrpcAdapter(HelloService& domain) : m_domain(domain) {}

    grpc::Status Greet(grpc::ServerContext* /*ctx*/,
                       const hello::v1::GreetRequest* request,
                       hello::v1::GreetResponse* response) override;

    grpc::Status Echo(grpc::ServerContext* /*ctx*/,
                      const hello::v1::EchoRequest* request,
                      hello::v1::EchoResponse* response) override;

    grpc::Status Tick(grpc::ServerContext* ctx,
                      const hello::v1::TickRequest* request,
                      grpc::ServerWriter<hello::v1::TickEvent>* writer) override;

private:
    HelloService& m_domain;
};

}  // namespace hello
