"""Test projects: export Consul-registered services into a test project,
and run its tests.

See :mod:`.engine` for the runner-neutral core, :mod:`.runs` for running,
and :mod:`.robot_aio` for the Robot Framework AIO adapter.
"""

from ...ports.test_project import (
    GroupMember,
    PlannedFile,
    RunArtifact,
    RunGroup,
    RunOptions,
    RunPlan,
    RunResult,
    RunSettings,
    ServiceExport,
    TestProjectConflict,
    TestProjectError,
    TestProjectRunner,
)
from .engine import (
    MANIFEST_NAME,
    available_runners,
    check_syntax,
    collect_proto_set,
    create_suite,
    write_project_file,
    describe,
    edit_file_view,
    export_service,
    find_service_protos,
    get_groups,
    get_run_settings,
    get_runner,
    groups_of,
    init_project,
    inspect_file,
    inspect_group,
    locate_service_proto,
    project_tree,
    proto_services,
    read_project_file,
    register_runner,
    set_groups,
    set_run_settings,
    validate_name,
)
from .robot_aio import RobotAioRunner, sync_links
from .runs import RUNS, RunManager

__all__ = [
    "GroupMember",
    "MANIFEST_NAME",
    "PlannedFile",
    "RUNS",
    "RobotAioRunner",
    "RunArtifact",
    "RunGroup",
    "RunManager",
    "RunOptions",
    "RunPlan",
    "RunResult",
    "RunSettings",
    "ServiceExport",
    "TestProjectConflict",
    "TestProjectError",
    "TestProjectRunner",
    "available_runners",
    "check_syntax",
    "collect_proto_set",
    "create_suite",
    "write_project_file",
    "describe",
    "edit_file_view",
    "export_service",
    "find_service_protos",
    "get_groups",
    "get_run_settings",
    "get_runner",
    "groups_of",
    "init_project",
    "inspect_file",
    "inspect_group",
    "locate_service_proto",
    "project_tree",
    "proto_services",
    "read_project_file",
    "register_runner",
    "set_groups",
    "set_run_settings",
    "sync_links",
    "validate_name",
]
