// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test_service.proto

#include "test_service.pb.h"
#include "test_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace test_service {
namespace v1 {

static const char* TestServiceService_method_names[] = {
  "/test_service.v1.TestServiceService/Echo",
  "/test_service.v1.TestServiceService/Add",
};

std::unique_ptr< TestServiceService::Stub> TestServiceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TestServiceService::Stub> stub(new TestServiceService::Stub(channel, options));
  return stub;
}

TestServiceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Echo_(TestServiceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Add_(TestServiceService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TestServiceService::Stub::Echo(::grpc::ClientContext* context, const ::test_service::v1::EchoRequest& request, ::test_service::v1::EchoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::test_service::v1::EchoRequest, ::test_service::v1::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Echo_, context, request, response);
}

void TestServiceService::Stub::async::Echo(::grpc::ClientContext* context, const ::test_service::v1::EchoRequest* request, ::test_service::v1::EchoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::test_service::v1::EchoRequest, ::test_service::v1::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Echo_, context, request, response, std::move(f));
}

void TestServiceService::Stub::async::Echo(::grpc::ClientContext* context, const ::test_service::v1::EchoRequest* request, ::test_service::v1::EchoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Echo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::test_service::v1::EchoResponse>* TestServiceService::Stub::PrepareAsyncEchoRaw(::grpc::ClientContext* context, const ::test_service::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::test_service::v1::EchoResponse, ::test_service::v1::EchoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Echo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::test_service::v1::EchoResponse>* TestServiceService::Stub::AsyncEchoRaw(::grpc::ClientContext* context, const ::test_service::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEchoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TestServiceService::Stub::Add(::grpc::ClientContext* context, const ::test_service::v1::AddRequest& request, ::test_service::v1::AddResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::test_service::v1::AddRequest, ::test_service::v1::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Add_, context, request, response);
}

void TestServiceService::Stub::async::Add(::grpc::ClientContext* context, const ::test_service::v1::AddRequest* request, ::test_service::v1::AddResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::test_service::v1::AddRequest, ::test_service::v1::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, std::move(f));
}

void TestServiceService::Stub::async::Add(::grpc::ClientContext* context, const ::test_service::v1::AddRequest* request, ::test_service::v1::AddResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::test_service::v1::AddResponse>* TestServiceService::Stub::PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::test_service::v1::AddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::test_service::v1::AddResponse, ::test_service::v1::AddRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Add_, context, request);
}

::grpc::ClientAsyncResponseReader< ::test_service::v1::AddResponse>* TestServiceService::Stub::AsyncAddRaw(::grpc::ClientContext* context, const ::test_service::v1::AddRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

TestServiceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TestServiceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TestServiceService::Service, ::test_service::v1::EchoRequest, ::test_service::v1::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TestServiceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::test_service::v1::EchoRequest* req,
             ::test_service::v1::EchoResponse* resp) {
               return service->Echo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TestServiceService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TestServiceService::Service, ::test_service::v1::AddRequest, ::test_service::v1::AddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TestServiceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::test_service::v1::AddRequest* req,
             ::test_service::v1::AddResponse* resp) {
               return service->Add(ctx, req, resp);
             }, this)));
}

TestServiceService::Service::~Service() {
}

::grpc::Status TestServiceService::Service::Echo(::grpc::ServerContext* context, const ::test_service::v1::EchoRequest* request, ::test_service::v1::EchoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TestServiceService::Service::Add(::grpc::ServerContext* context, const ::test_service::v1::AddRequest* request, ::test_service::v1::AddResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test_service
}  // namespace v1

