"""gRPC inbound adapter for :class:`HelloService`.

Thin mapping layer between the generated ``hello_pb2_grpc`` stub and the
pure-Python domain object.  All transport concerns live here; all business
rules live in ``domain/``.
"""

from __future__ import annotations

import logging

import grpc

# Generated by grpc_tools — see scripts/generate_protos.py.
from proto import hello_pb2, hello_pb2_grpc  # type: ignore[import-not-found]

from domain.hello_service import HelloService

logger = logging.getLogger(__name__)


class HelloGrpcAdapter(hello_pb2_grpc.HelloServiceServicer):
    """Maps gRPC calls to :class:`HelloService` methods."""

    def __init__(self, domain: HelloService) -> None:
        self._domain = domain

    async def Greet(
        self,
        request: hello_pb2.GreetRequest,
        context: grpc.aio.ServicerContext,
    ) -> hello_pb2.GreetResponse:
        message = await self._domain.greet(request.name)
        return hello_pb2.GreetResponse(message=message)

    async def Echo(
        self,
        request: hello_pb2.EchoRequest,
        context: grpc.aio.ServicerContext,
    ) -> hello_pb2.EchoResponse:
        payload = await self._domain.echo(request.payload)
        return hello_pb2.EchoResponse(payload=payload)

    async def Tick(
        self,
        request: hello_pb2.TickRequest,
        context: grpc.aio.ServicerContext,
    ):
        """Server-streaming RPC; forwards ``(seq, msg)`` tuples as TickEvent."""
        interval = request.interval_ms or 1000
        async for seq, msg in self._domain.tick(request.count, interval):
            if context.cancelled():
                logger.debug("Tick stream cancelled by client.")
                return
            yield hello_pb2.TickEvent(sequence=seq, message=msg)
