#include "MainWindow.h"
#include "ui_MainWindow.h"   // generated by AUTOUIC from MainWindow.ui

// Qt-style protobuf + gRPC stubs generated by qt_add_protobuf and
// qt_add_grpc(... CLIENT) (CMake) or proto/generate_qt_stubs.bat
// (one-shot).  File names follow `<.proto stem>.qpb.h` and
// `<stem>_client.grpc.qpb.h`.
#include "com_config_device.qpb.h"
#include "com_config_device_client.grpc.qpb.h"
#include "power_device.qpb.h"
#include "power_device_client.grpc.qpb.h"

// Qt 6.8+: the URL goes directly to QGrpcHttp2Channel's ctor;
// QGrpcChannelOptions is no longer the URL container — it just carries
// per-channel tweaks like deadline / metadata.
#include <QtGrpc/QGrpcHttp2Channel>

#include <QCheckBox>
#include <QComboBox>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QLineEdit>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QPlainTextEdit>
#include <QPushButton>
#include <QStringList>
#include <QTextEdit>
#include <QUrl>

namespace {

// One typed Client per service, kept alive for the lifetime of the
// process.  Each Client is stateless except for its attached channel;
// we re-attach in applyChannelUrl() whenever the user clicks Connect.
Com_Setup_Device::ComSetupDeviceService::Client& com_setup_device_service_client() { static Com_Setup_Device::ComSetupDeviceService::Client c; return c; }
power_device::PowerSupplyService::Client& power_supply_service_client() { static power_device::PowerSupplyService::Client c; return c; }

}  // namespace

MainWindow::MainWindow(QWidget* parent)
    : QWidget(parent), ui(new Ui::MainWindow), m_net(new QNetworkAccessManager(this)) {
    ui->setupUi(this);

    setupDispatch();

    for (const auto& s : m_serviceList) ui->serviceCombo->addItem(s);
    onServiceChanged(0);

    // Default the Consul service-name field to the first service in
    // the picker (saves a paste).
    if (!m_serviceList.isEmpty())
        ui->serviceNameEdit->setText(m_serviceList.first().toLower().replace(' ', '_'));

    connect(ui->connectButton, &QPushButton::clicked, this, &MainWindow::onConnectClicked);
    connect(ui->sendButton,    &QPushButton::clicked, this, &MainWindow::onSendClicked);
    connect(ui->serviceCombo,  QOverload<int>::of(&QComboBox::currentIndexChanged),
            this, &MainWindow::onServiceChanged);
    connect(ui->useConsul,     &QCheckBox::toggled, this, &MainWindow::onUseConsulToggled);
    onUseConsulToggled(ui->useConsul->isChecked());
}

MainWindow::~MainWindow() {
    delete ui;
}

void MainWindow::onServiceChanged(int) {
    ui->methodCombo->clear();
    for (const auto& m : m_methodsByService.value(ui->serviceCombo->currentText()))
        ui->methodCombo->addItem(m);
}

void MainWindow::onUseConsulToggled(bool checked) {
    ui->consulUrlEdit->setEnabled(checked);
    ui->serviceNameEdit->setEnabled(checked);
    ui->hostEdit->setEnabled(!checked);
}

void MainWindow::onConnectClicked() {
    if (ui->useConsul->isChecked()) {
        resolveViaConsul();
    } else {
        applyChannelUrl(QUrl(ui->hostEdit->text()));
    }
}

void MainWindow::resolveViaConsul() {
    const QString consul = ui->consulUrlEdit->text().trimmed();
    const QString svc    = ui->serviceNameEdit->text().trimmed();
    if (consul.isEmpty() || svc.isEmpty()) {
        ui->statusLabel->setText("Consul URL and service name are required.");
        return;
    }
    QUrl url(consul + "/v1/health/service/" + svc + "?passing=true");
    ui->statusLabel->setText(QStringLiteral("Resolving %1 via Consul...").arg(svc));

    auto* reply = m_net->get(QNetworkRequest(url));
    connect(reply, &QNetworkReply::finished, this, [this, reply, svc]() {
        reply->deleteLater();
        if (reply->error() != QNetworkReply::NoError) {
            ui->statusLabel->setText(
                QStringLiteral("Consul error: %1").arg(reply->errorString()));
            return;
        }
        QJsonParseError perr;
        const QJsonDocument doc = QJsonDocument::fromJson(reply->readAll(), &perr);
        if (perr.error != QJsonParseError::NoError || !doc.isArray()) {
            ui->statusLabel->setText("Consul returned non-JSON or non-array.");
            return;
        }
        const QJsonArray arr = doc.array();
        if (arr.isEmpty()) {
            ui->statusLabel->setText(
                QStringLiteral("No healthy '%1' registered in Consul.").arg(svc));
            return;
        }
        // Pick the first healthy entry.  Production would round-robin.
        const QJsonObject entry   = arr.first().toObject();
        const QJsonObject service = entry.value("Service").toObject();
        QString addr = service.value("Address").toString();
        if (addr.isEmpty())
            addr = entry.value("Node").toObject().value("Address").toString();
        const int port = service.value("Port").toInt();
        if (addr.isEmpty() || port <= 0) {
            ui->statusLabel->setText("Consul entry missing Address / Port.");
            return;
        }
        const QUrl target(QStringLiteral("http://%1:%2").arg(addr).arg(port));
        ui->hostEdit->setText(target.toString());   // surface for visibility
        applyChannelUrl(target);
    });
}

void MainWindow::applyChannelUrl(const QUrl& url) {
    // Qt 6.8+: pass the URL directly.  Add a QGrpcChannelOptions arg
    // for deadline / metadata tweaks if you need them.
    m_channel = std::make_shared<QGrpcHttp2Channel>(url);
    if (!m_channel) {
        ui->statusLabel->setText("channel failed");
        return;
    }
    // Re-attach every typed client to the new channel.
    com_setup_device_service_client().attachChannel(m_channel);
        power_supply_service_client().attachChannel(m_channel);
    ui->statusLabel->setText(QStringLiteral("channel ready: %1").arg(url.toString()));
}

void MainWindow::onSendClicked() {
    if (!m_channel) {
        ui->statusLabel->setText("Click Connect first.");
        return;
    }
    const QString svc = ui->serviceCombo->currentText();
    const QString rpc = ui->methodCombo->currentText();
    const QString key = svc + QChar('.') + rpc;
    const QByteArray body = ui->requestEdit->toPlainText().toUtf8();

    auto it = m_dispatch.find(key);
    if (it == m_dispatch.end()) {
        ui->statusLabel->setText(QStringLiteral("No dispatcher for %1").arg(key));
        return;
    }

    ui->statusLabel->setText(QStringLiteral("Calling %1 ...").arg(key));
    ui->responseEdit->clear();
    it.value()(body, [this](bool ok, const QString& result) {
        ui->responseEdit->setPlainText(result);
        ui->statusLabel->setText(ok ? "OK" : "FAILED");
    });
}

// =======================================================================
// Dispatch table — one lambda per (service, method) pair.
//
// Each lambda calls invokeRpc<Req, Resp>(...) with a small inner lambda
// that returns the typed Client's reply.  invokeRpc handles JSON parse,
// signal hookup, response read, JSON serialize.  Adding a method = one
// new line; no boilerplate is repeated.
// =======================================================================

void MainWindow::setupDispatch() {
    m_serviceList << "ComSetupDeviceService";
    m_methodsByService["ComSetupDeviceService"] = { "SetInterfaceType", "GetInterfaceType", "SetInterfaceConfig", "GetInterfaceConfig", "LoadInterfaceConfig", "Connect", "DisConnect", "GetConnectState" };

    m_dispatch.insert("ComSetupDeviceService.SetInterfaceType",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::Com_Setup_Device::InterfaceTypeRequest, ::Com_Setup_Device::CommandResponse>(j, d,
                [](const ::Com_Setup_Device::InterfaceTypeRequest& r) { return com_setup_device_service_client().SetInterfaceType(r); });
        });

    m_dispatch.insert("ComSetupDeviceService.GetInterfaceType",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::Com_Setup_Device::Empty, ::Com_Setup_Device::GetInterfaceTypeResponse>(j, d,
                [](const ::Com_Setup_Device::Empty& r) { return com_setup_device_service_client().GetInterfaceType(r); });
        });

    m_dispatch.insert("ComSetupDeviceService.SetInterfaceConfig",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::Com_Setup_Device::SetInterfaceConfigRequest, ::Com_Setup_Device::CommandResponse>(j, d,
                [](const ::Com_Setup_Device::SetInterfaceConfigRequest& r) { return com_setup_device_service_client().SetInterfaceConfig(r); });
        });

    m_dispatch.insert("ComSetupDeviceService.GetInterfaceConfig",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::Com_Setup_Device::SetInterfaceConfigRequest, ::Com_Setup_Device::GetInterfaceConfigResponse>(j, d,
                [](const ::Com_Setup_Device::SetInterfaceConfigRequest& r) { return com_setup_device_service_client().GetInterfaceConfig(r); });
        });

    m_dispatch.insert("ComSetupDeviceService.LoadInterfaceConfig",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::Com_Setup_Device::LoadInterfaceConfigRequest, ::Com_Setup_Device::CommandResponse>(j, d,
                [](const ::Com_Setup_Device::LoadInterfaceConfigRequest& r) { return com_setup_device_service_client().LoadInterfaceConfig(r); });
        });

    m_dispatch.insert("ComSetupDeviceService.Connect",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::Com_Setup_Device::Empty, ::Com_Setup_Device::CommandResponse>(j, d,
                [](const ::Com_Setup_Device::Empty& r) { return com_setup_device_service_client().Connect(r); });
        });

    m_dispatch.insert("ComSetupDeviceService.DisConnect",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::Com_Setup_Device::Empty, ::Com_Setup_Device::CommandResponse>(j, d,
                [](const ::Com_Setup_Device::Empty& r) { return com_setup_device_service_client().DisConnect(r); });
        });

    m_dispatch.insert("ComSetupDeviceService.GetConnectState",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::Com_Setup_Device::Empty, ::Com_Setup_Device::GetConnectStateResponse>(j, d,
                [](const ::Com_Setup_Device::Empty& r) { return com_setup_device_service_client().GetConnectState(r); });
        });

    m_serviceList << "PowerSupplyService";
    m_methodsByService["PowerSupplyService"] = { "SetSubDeviceType", "GetSubDeviceType", "GetSubDeviceTypeChannelCount", "GetSubDeviceType_ListCount", "GetSubDeviceType_ID", "GetSubDeviceType_Name", "InitDevice", "SetVoltage", "SetCurrentLimit", "SetOutputEnabled", "ReadCurrent", "ReadVoltage" };

    m_dispatch.insert("PowerSupplyService.SetSubDeviceType",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::SubDeviceTypeRequest, ::power_device::CommandResponse>(j, d,
                [](const ::power_device::SubDeviceTypeRequest& r) { return power_supply_service_client().SetSubDeviceType(r); });
        });

    m_dispatch.insert("PowerSupplyService.GetSubDeviceType",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::Empty, ::power_device::GetSubDeviceTypeResponse>(j, d,
                [](const ::power_device::Empty& r) { return power_supply_service_client().GetSubDeviceType(r); });
        });

    m_dispatch.insert("PowerSupplyService.GetSubDeviceTypeChannelCount",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::Empty, ::power_device::ChannelCountResponse>(j, d,
                [](const ::power_device::Empty& r) { return power_supply_service_client().GetSubDeviceTypeChannelCount(r); });
        });

    m_dispatch.insert("PowerSupplyService.GetSubDeviceType_ListCount",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::Empty, ::power_device::GetSubDeviceTypeListCountResponse>(j, d,
                [](const ::power_device::Empty& r) { return power_supply_service_client().GetSubDeviceType_ListCount(r); });
        });

    m_dispatch.insert("PowerSupplyService.GetSubDeviceType_ID",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::SubDeviceTypeRequest, ::power_device::GetSubDeviceTypeIDResponse>(j, d,
                [](const ::power_device::SubDeviceTypeRequest& r) { return power_supply_service_client().GetSubDeviceType_ID(r); });
        });

    m_dispatch.insert("PowerSupplyService.GetSubDeviceType_Name",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::SubDeviceTypeRequest, ::power_device::GetSubDeviceTypeNameResponse>(j, d,
                [](const ::power_device::SubDeviceTypeRequest& r) { return power_supply_service_client().GetSubDeviceType_Name(r); });
        });

    m_dispatch.insert("PowerSupplyService.InitDevice",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::Empty, ::power_device::CommandResponse>(j, d,
                [](const ::power_device::Empty& r) { return power_supply_service_client().InitDevice(r); });
        });

    m_dispatch.insert("PowerSupplyService.SetVoltage",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::SetVoltageRequest, ::power_device::CommandResponse>(j, d,
                [](const ::power_device::SetVoltageRequest& r) { return power_supply_service_client().SetVoltage(r); });
        });

    m_dispatch.insert("PowerSupplyService.SetCurrentLimit",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::SetCurrentLimitRequest, ::power_device::CommandResponse>(j, d,
                [](const ::power_device::SetCurrentLimitRequest& r) { return power_supply_service_client().SetCurrentLimit(r); });
        });

    m_dispatch.insert("PowerSupplyService.SetOutputEnabled",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::SetOutputEnabledRequest, ::power_device::CommandResponse>(j, d,
                [](const ::power_device::SetOutputEnabledRequest& r) { return power_supply_service_client().SetOutputEnabled(r); });
        });

    m_dispatch.insert("PowerSupplyService.ReadCurrent",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::ChannelRequest, ::power_device::GetMeasurementsResponse>(j, d,
                [](const ::power_device::ChannelRequest& r) { return power_supply_service_client().ReadCurrent(r); });
        });

    m_dispatch.insert("PowerSupplyService.ReadVoltage",
        [this](const QByteArray& j, DoneFn d) {
            invokeRpc<::power_device::ChannelRequest, ::power_device::GetMeasurementsResponse>(j, d,
                [](const ::power_device::ChannelRequest& r) { return power_supply_service_client().ReadVoltage(r); });
        });
}
